### ISSUE TITLE
Optimize the way to simulate human typing

### ISSUE THREAD

**Issue by ysmood** [charmbracelet/vhs#107]
The `SlowMotion` of rod, it's not designed for production usage, it has a lot of side effects:

https://github.com/charmbracelet/vhs/blob/1508f495c2016d7364244924fc4123b70c13f55b/vhs.go#L71

Better to control the typing speed on vhs itself.

**Comment by muesli** [comment]
Thank you @ysmood, we'll get to that asap!

**Comment by maaslalani** [comment]
Thanks for the heads up @ysmood, I actually did it normally before so we can probably revert this commit: https://github.com/charmbracelet/vhs/commit/affecba8db434fd6bd65f9a2d3fdb439ee0957fc

PS: Thanks so much for `go-rod`, it's a fantastic project ❤️
