### ISSUE TITLE
Xcode is too outdated

### ISSUE THREAD

**Issue by userbradley** [charmbracelet/vhs#123]
Howdy,

Mac users who have updated to the latest version of mac osx may get the below issue

`Error: Your Xcode (14.0.1) is too outdated`

I've put together a page for this, you're welcome to include it:

[Documentation](https://documentation.breadnet.co.uk/kb/linux-cli/your-xcode-is-too-outdated/)

It's just a simple case of 

```
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install
```

Thought it would be worth while letting you know about this in case you get some issues around that :)

**Comment by caarlos0** [comment]
this will also affect homebrew, git (I think), and many others.

It might be needed to download the RC version from apple developer's website even.

That said, we can close this, and leave it as documentation if anyone else face this issue.

Thanks!
