### ISSUE TITLE
Include other tapes

### ISSUE THREAD

**Issue by Airblader** [charmbracelet/vhs#133]
I would love to have some

```
Include foo.tape
```

command to modularize tapes a little bit. For example, one may require some setup (logging into an application), or want some "signoff phrase" at the end of a session, which are the same across different tapes.

**Comment by maaslalani** [comment]
Hey this is a really good idea! I definitely want to have something like this.

**Comment by Airblader** [comment]
> Fwiw we already have plans of adding Functions / Macros to the language!

Oh that is awesome. I didn't dare ask for that, but was about to.

> The Include makes things slightly more dependent on multiple files which is obviously less nice than having 1 file map to 1 output.

I feel the hesitation. In i3/i3 it took us years to be convinced to add an include directive, but it is such a quality of life change.

It really doesn't need to be fancy. Just a "replace this line with the contents of that file", basically.

**Comment by maaslalani** [comment]
> It really doesn't need to be fancy. Just a "replace this line with the contents of that file", basically.

Totally, this basically gives you `Macro`s without needing to implement much new syntax since the whole file is essentially a Macro. I think I am sold 😄

**Comment by melMass** [comment]
I came to open this exact issue, having a way to share a base setup when documenting many independent gifs would remove a lot of copy paste :)

**Comment by bakks** [comment]
Plus one for this feature request!

**Comment by elmarsan** [comment]
Hey @maaslalani I'd love to work on this one.

I've got a few ideas about how to approach it but I believe would be great to have some guidelines. 
How would you do it? For example a new command that executes another tape? Like @bakks proposed in #220.

**Comment by maaslalani** [comment]
Hey @elmarsan, awesome that you're interested in this issue! My thinking is that you have a command (let's call it `Include` or `Source`) that you can use to reference a `.tape` file (from the relative path of the VHS invocation or tape file):

```
Include ./foo.tape
```

I think the only things I would expect to have are that it shows me that the command currently running is being sourced from a different file, and if there are any runtime or parsing errors it tells me that it is from that file (and the line number) which makes it a bit harder than simply copying and pasting the contents of the file into the master tape file which would skew all of the line numbers.

**Comment by elmarsan** [comment]
> Hey @elmarsan, awesome that you're interested in this issue! My thinking is that you have a command (let's call it `Include` or `Source`) that you can use to reference a `.tape` file (from the relative path of the VHS invocation or tape file):
> 
> ```
> Include ./foo.tape
> ```
> 
> I think the only things I would expect to have are that it shows me that the command currently running is being sourced from a different file, and if there are any runtime or parsing errors it tells me that it is from that file (and the line number) which makes it a bit harder than simply copying and pasting the contents of the file into the master tape file which would skew all of the line numbers.

Great, I think I'm ready to hands on with this feature, thanks!

**Comment by elmarsan** [comment]
This one can be closed, as we've added the feature in #276 

But remember the command is not ~~Include~~ it's `Source`

**Comment by maaslalani** [comment]
Thanks again @elmarsan , closing this one as well.
