### ISSUE TITLE
go install results in a checksum error

### ISSUE THREAD

**Issue by ismail** [charmbracelet/vhs#134]
```
❯ go version
go version go1.19.3 linux/amd64

❯ go install github.com/charmbracelet/vhs@latest
go: downloading github.com/charmbracelet/vhs v0.1.1
go: github.com/charmbracelet/vhs@latest: github.com/charmbracelet/vhs@v0.1.1: verifying module: checksum mismatch
        downloaded: h1:EZCqR9qwpqg0j4VD2cy8a/WlTAs0uaUgU4RW0/pC1D8=
        sum.golang.org: h1:SSZYYmO4FrknkqC8J+X8pVLbgEy+StMSpk4b4sYtJ00=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by maaslalani** [comment]
Hmm, unfortunately I am unable to reproduce:

<img width="618" alt="image" src="https://user-images.githubusercontent.com/42545625/199513672-0f21493b-779e-4274-885f-618d31a739e1.png">

**Comment by ismail** [comment]
Can you try with

```
export GOPROXY=direct
```

**Comment by maaslalani** [comment]
<img width="703" alt="image" src="https://user-images.githubusercontent.com/42545625/199524497-6c0b8d77-cb8c-4afb-86e2-1337c0ce1112.png">

**Comment by maaslalani** [comment]
@ismail is this still not working for you if you try it again?  Are you able to clear the go cache by any chance?

**Comment by maaslalani** [comment]
Ha, actually when I `go clean -modcache` I can reproduce the error:

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/42545625/199525047-a2e37338-9308-461d-a864-f0bc4303f4be.png">

**Comment by maaslalani** [comment]
@ismail We just released a new version of VHS so this should now be fixed but please feel free to reopen this issue if it is not!
