### ISSUE TITLE
Asciicast converter

### ISSUE THREAD

**Issue by rsteube** [charmbracelet/vhs#143]
With `asciinema rec --stdin` keyboard inputs are recorded in [asciinema](https://github.com/asciinema/asciinema).
The [event stream](https://github.com/asciinema/asciinema/blob/develop/doc/asciicast-v2.md#event-stream) (`i` => input) can then be converted to a `tape` file (repetitive keys and text should be collected to a single instruction).

## cast2tape
```sh
#!/bin/sh

echo "Hide"
echo "Type $(head -n 1 "$1" | jq '.env.SHELL')"
echo "Enter"
echo "Show"
echo
echo "Set TypingSpeed 0.1"
echo

backspace=""

tail -n +2 "$1" \
  | jq --raw-output '. | select(.[1] == "i" ) | .[2]' \
  | sed 's/\([\r\t'"$backspace"']\)/\1\n/' \
  | sed -z 's/\n\([^\r\t'"$backspace"']\)/\1/g' \
  | sed -e 's/\([^\r\t'"$backspace"'].*\)/Type "\1"/' -e 's/\r/Enter/' -e 's/\t/Tab/' -e 's/'"$backspace"'/Backspace/'
```

## asciicast

[![asciicast](https://asciinema.org/a/SAfH0ImjalxzbD0CFquocSf4E.svg)](https://asciinema.org/a/SAfH0ImjalxzbD0CFquocSf4E)

## tape

```sh
Hide
Type "elvish"
Enter
Show

Set TypingSpeed 0.1

Type "echo test"
Backspace
Backspace
Backspace
Backspace
Type "example"
Enter
Type "vhs "
Tab
Tab
Tab
Tab
Tab
Tab
Tab
Enter
Enter
Type "exit"
Enter
```

## gif

![out](https://user-images.githubusercontent.com/9090290/200116461-0d2c92b4-9745-4ed5-979c-ea3402440acb.gif)

**Comment by maaslalani** [comment]
This is quite cool @rsteube, just as a heads up though. We have implemented our own `vhs record` feature in #135.

You can try it out with:
```
vhs record
```

**Comment by rsteube** [comment]
Yeah, saw that a bit too late. Thought it would take a while till that is added.

**Comment by rsteube** [comment]
Moved it to https://github.com/rsteube/cast2tape. @maaslalani might be a good idea to make some functions available as library in the future.
