### ISSUE TITLE
Images appearing

### ISSUE THREAD

**Issue by AlexDias95** [charmbracelet/vhs#144]
I am trying to do the example in the folder examples/images but the output gif does not show images, what is wrong?

**Comment by griimick** [comment]
Please share more context like the example file name, the command you ran to generate the gif, your vhs setup and your environment details.

**Comment by AlexDias95** [comment]
My environment is a MacOS 16 with VHS and lsix installed.

My tape file:
```sh
Type "lsix test1.jpeg"
Enter
Sleep 3s
```

Result:


![out](https://user-images.githubusercontent.com/47275399/200123658-854ded63-cfc8-4e8b-83f9-4093afd97833.gif)

But if I ran the same command on my terminal I get:

<img width="312" alt="Captura de ecrã 2022-11-05, às 14 03 20" src="https://user-images.githubusercontent.com/47275399/200123699-a63aac6c-5f33-46f3-be75-1e97f2058440.png">

**Comment by griimick** [comment]
Thanks. I think sixel is not yet supported in VHS recording. This feature is in works ig.

**Comment by AlexDias95** [comment]
Ohhh, so there is no way to show images using VHS right now? :/

**Comment by maaslalani** [comment]
@AlexDias95 Yes, sorry image/sixel support is not currently supported but will be in the future!

**Comment by maaslalani** [comment]
I will close this issue as we are tracking this in #43, thank you! I will also delete the images example as that was accidentally committed.
