### ISSUE TITLE
ttyd not found and version outdated

### ISSUE THREAD

**Issue by jcubic** [charmbracelet/vhs#148]
I've installed ttyd after libwebsockets and libuv that was required.

I got this output:

```
$ ttyd --version
ttyd version 1.7.2-25e9522
$ vhs
Error: ttyd is not installed. Install it from: https://github.com/tsl0922/ttyd
...
ttyd is not installed. Install it from: https://github.com/tsl0922/ttyd
$ vhs demo.tape 
Error: ttyd version (<nil>) is out of date, VHS requires 1.7.1
Install the latest version from: https://github.com/tsl0922/ttyd
```

I've tried to install vhs as RPM package on Fedora and with `go install` command both give the same error.

**Comment by maaslalani** [comment]
Taking a look now! Thanks for creating this issue.

**Comment by maaslalani** [comment]
What version of VHS are you using @jcubic?

**Comment by jcubic** [comment]
I've tried both installed latest from source.

**Comment by jcubic** [comment]
The problem is with the installation of ttyd. I've asked on Unix StackExchange [How to install ttyd from source on Fedora?](https://unix.stackexchange.com/q/724172/1806).

**Comment by jcubic** [comment]
I think that I can close this. Since this is not related to vhs.

**Comment by maaslalani** [comment]
@jcubic Does this issue help by any chance:
https://github.com/charmbracelet/vhs/issues/45
