### ISSUE TITLE
Not using default browser

### ISSUE THREAD

**Issue by SunPodder** [charmbracelet/vhs#150]
I have firefox installed. Then why does it downloading chromium?

**Comment by caarlos0** [comment]
vhs uses go-rod, which only supports chromium

https://github.com/go-rod/rod

**Comment by SunPodder** [comment]
Is there any planning to support other browsers in future?

**Comment by SunPodder** [comment]
@caarlos0 I have chromium installed this time. Still it's trying to download it.
```bash
$ vhs < demo.tape
[launcher.Browser]2023/01/12 10:42:56 try to find the fastest host to download the browser binary
[launcher.Browser]2023/01/12 10:42:56 check https://storage.googleapis.com/chromium-browser-snapshots//1033860/     
[launcher.Browser]2023/01/12 10:42:56 check https://registry.npmmirror.com/-/binary/chromium-browser-snapshots//1033860/
[launcher.Browser]2023/01/12 10:42:56 check https://playwright.azureedge.net/builds/chromium/1033860/chromium-linux-arm64.zip
```

**Comment by bashbunni** [comment]
Hey @SunPodder I saw you asked [this](https://github.com/go-rod/rod/issues/803) on the upstream dependency. I'll let them answer than over on `rod` as it is not behaviour handled by `vhs`
