### ISSUE TITLE
Ability to wait for long-running process to finish before continuing tape

### ISSUE THREAD

**Issue by pmonks** [charmbracelet/vhs#151]
It would be ideal if there were a way to wait for a long-running process to finish before the tape continues.  For example:
```
Output demo.gif
Set FontSize 12
Set Width 800
Set Height 500
Type "clojure -T:build test"
Enter
WaitForProcessTermination
Sleep 5s
```

Note that `WaitForProcessTermination` is just a placeholder - I'm sure the vhs team have a much better idea of an appropriate command name.

**Comment by maaslalani** [comment]
Agreed! We will definitely add this this feature if it is possible.

We're tracking this in: https://github.com/charmbracelet/vhs/issues/70

**Comment by pmonks** [comment]
My apologies for not finding this - I did look, but clearly not well enough.  😉
