### ISSUE TITLE
How would I change default shell?

### ISSUE THREAD

**Issue by Zliced13** [charmbracelet/vhs#158]
It keeps using **bash**, which I don't want. Could it please use **pwsh** instead?
![demo](https://user-images.githubusercontent.com/101912712/201452154-80acb128-8987-4409-851d-ea6561f4f48a.gif)

**Comment by maaslalani** [comment]
Hey @Zliced13 what version of VHS are you using? The latest `main` should fix this, let me know if it does not.

**Comment by Zliced13** [comment]
I'm using 0.1.1, installed with scoop.

**Comment by melMass** [comment]
@maaslalani on 0.1.1 `Set Shell nu` returns

```ruby
File: demo.tape
 46 │ Set Shell nu
          ^^^^^ Unknown setting: Shell
```

**Comment by melMass** [comment]
@Zliced13 If I understand it right, this feature is not yet in a release but only on Github for now.
One solution is to call pwsh as the first step:

```vhs
Type "pwsh"
Enter
```

**Comment by Zliced13** [comment]
Oh ok good idea

**Comment by maaslalani** [comment]
@melMass We just released `0.2.0` which includes the `Set Shell` feature please let me know if it works correctly for you!

@Zliced13 Can you upgrade to `0.2.0` and try the following:

```
Set Shell pwsh
```

**Comment by Zliced13** [comment]
I'll try it out @maaslalani.

**Comment by Zliced13** [comment]
@maaslalani I get this error when I use `Set Shell pwsh` in my configuration file, see the following GIF below:
![test](https://user-images.githubusercontent.com/101912712/203650537-4b60eccc-9b09-4f07-86a4-d94b7217ea13.gif)

[test.demo.tape.txt](https://github.com/charmbracelet/vhs/files/10079294/test.demo.tape.txt)

**Comment by melMass** [comment]
Thanks @maaslalani.
This issue can be closed I think!

@Zliced13 try this:

```ruby
Output ./Downloads/test.gif
Set FontSize 32
Set Width 1200
Set Height 600
Set LoopOffset 50%
Set Shell pwsh

# pwsh profile loading times aren't great 
# I think this is why you have that issue
Sleep 1000ms

Type ". ./MyScoop/bin/test.ps1"
Sleep 500ms
Enter
Sleep 10s
```

![test](https://user-images.githubusercontent.com/7041726/203681519-0ea8cc8a-600d-45b1-8dda-dae6eebee41e.gif)

**Comment by Zliced13** [comment]
I think this will fix it for me, I will close this issue now.
