### ISSUE TITLE
:pray:  Feature Request > VSCode extension :nerd_face: 

### ISSUE THREAD

**Issue by adriens** [charmbracelet/vhs#162]
# :grey_question: Context

Currently, there is a quite important amount of drectives, and while developing a `tape`, I : 

- Keep the `VHS` `README.md` opened
- Switch between my source code and README
- Would like to get some colors

# :pray: Feature request

- Implement color syntaxing
- Autocomplete of `VHS` supported directives

**Comment by muesli** [comment]
There is a VSCode extension for syntax highlighting: https://marketplace.visualstudio.com/items?itemName=griimick.vhs

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/202019421-65240020-0832-405f-a8c1-c7982c4496bd.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/202019524-6dd57fca-202e-4600-b5f6-4364e774ed9c.png)

**Comment by adriens** [comment]
Thanks @muesli

**Comment by griimick** [comment]
Just putting it out here. Autocompletion is wip and should be available in next release.

**Comment by adriens** [comment]
Awesome :clap:

**Comment by maaslalani** [comment]
That's really awesome @griimick. We should probably make a `vhs-cmp` for neovim as well!

**Comment by adriens** [comment]
> That's really awesome @griimick. We should probably make a `vhs-cmp` source for neovim as well!

I though about it too :smile_cat:

**Comment by adriens** [comment]
BTW https://github.com/griimick/vscode-vhs

**Comment by caarlos0** [comment]
> That's really awesome @griimick. We should probably make a `vhs-cmp` source for neovim as well!

or a lsp server 👀
