### ISSUE TITLE
feature-request: allow screenshots / image output

### ISSUE THREAD

**Issue by FalcoSuessgott** [charmbracelet/vhs#165]
Hi,

i think it would be nice if `vhs` would allow .jpg, .svg or .png as an output format and thus be able to create a screenshot of the terminal once it has been succesfully rendered, similar to https://github.com/carbon-app/carbon.

Maybe the last frame of the gif can be used for that purpose.

**Comment by stdevel** [comment]
Great idea, I'd also love to see this happen. I'm creating a lot of screenshots for training material - the last reason for me to keep using Carbon. :)

**Comment by caarlos0** [comment]
fwiw you can add a dir output, which will then create all frames as png...

**Comment by adriens** [comment]
Yes, that would be great to be able to trigger screenshots at some specifc points in the scenario.... for example vy implementing a new command like : 

`Impr` or `Screnshot`

**Comment by maaslalani** [comment]
This is definitely on the road map, we want to build a feature that just allows for sharing really nice code screenshots.

**Comment by adriens** [comment]
Awesome :clap:

**Comment by maaslalani** [comment]
Screenshots were recently introduced in https://github.com/charmbracelet/vhs/pull/311 thanks to @elmarsan!
