### ISSUE TITLE
Using pre-defined themes seems to have no effect

### ISSUE THREAD

**Issue by blacktop** [charmbracelet/vhs#167]
I tried 5 themes and it didn't change the style at all, however, the explicit one from the README did work, however.

Set Theme { "name": "Whimsy", "black": "#535178", "red": "#ef6487", "green": "#5eca89", "yellow": "#fdd877", "blue": "#65aef7", "magenta": "#aa7ff0", "cyan": "#43c1be", "white": "#ffffff", "brightBlack": "#535178", "brightRed": "#ef6487", "brightGreen": "#5eca89", "brightYellow": "#fdd877", "brightBlue": "#65aef7", "brightMagenta": "#aa7ff0", "brightCyan": "#43c1be", "brightWhite": "#ffffff", "background": "#29283b", "foreground": "#b3b0d6", "selection": "#3d3c58", "cursor": "#b3b0d6" }

That one works, but say `Set Theme "nord"` does not.

**Comment by blacktop** [comment]
❯ vhs -v
vhs version v0.1.1 (b023c66)

**Comment by maaslalani** [comment]
Are you able to build from the latest main code and confirm if that works for you?

```bash
go install github.com/charmbracelet/vhs@main
# or
brew install --HEAD vhs
```

We should be releasing a new version of VHS soon!

**Comment by blacktop** [comment]
`go install github.com/charmbracelet/vhs@main` worked like a... Charm.    See what I did there? 😏
