### ISSUE TITLE
vhs v0.2 record return unsupported in windows

### ISSUE THREAD

**Issue by lost22git** [charmbracelet/vhs#180]
![image](https://user-images.githubusercontent.com/65008815/204180121-386316ee-117f-4ca1-a170-7e3416a29ec6.png)

**Comment by iqfareez** [comment]
Same issue. How do you solve it?

**Comment by lost22git** [comment]
@iqfareez  

No way, maybe the team doesn't care about it.

The team's work (e.g gum) has been poorly supported on the windows platform.

## Something that hopefully works for you:
* [ScreenToGif](https://github.com/NickeManarin/ScreenToGif)
* [terminalizer](https://github.com/faressoft/terminalizer)

**Comment by iqfareez** [comment]
I see. Thank you for the alternatives suggested. 👍

**Comment by Jonathan-Zollinger** [comment]
I've also started encountering this
