### ISSUE TITLE
Record mode cannot deal with quotes

### ISSUE THREAD

**Issue by Airblader** [charmbracelet/vhs#181]
What better way to report an issue than with a tape 🚀

```
$ vhs record > /tmp/test.tape
> echo '"'
> exit

$ cat /tmp/test.tape
Sleep 500ms
Type 'echo '"''
Enter

$ vhs < /tmp/test.tape
Sleep 500ms
Type echo  ''
Enter 1
Creating GIF...
```

Side note: quotes in general has been a bit of a pain point for me working with VHS.

**Comment by Airblader** [comment]
> Side note: quotes in general has been a bit of a pain point for me working with VHS.

The only way I could find so far is this:

```
Type "echo '"
Type '"'
Type "'"
```

This is really unergonomic, though, and it occurs quite frequently if you want to e.g. to some JSON on the command line, like

```
$ echo '{"foo": "bar"}' | jq
```

**Comment by maaslalani** [comment]
We actually recently introduced backticks as a string delimiter to handle this single + double quote issue.

We can use that for record mode:

```
Type `echo "hello 'quote`"`
```

**Comment by Airblader** [comment]
Oh, that is awesome to hear, thanks! The bug still stands, of course.

**Comment by maaslalani** [comment]
Totally! We will fix the bug in record mode, for sure. Thank you for reporting it 🙂

**Comment by maaslalani** [comment]
@Airblader This should be fixed now 😄
