### ISSUE TITLE
:stop_sign: Unable to use vhs anymore > brew >  (ttyd version (1.7.1) is out of date, VHS requires 1.7.2)

### ISSUE THREAD

**Issue by adriens** [charmbracelet/vhs#184]
# :grey_question: Description

Hi, since this morning I'm stuck with `vhs` because of `ttyd` on `brew` : 

![image](https://user-images.githubusercontent.com/5235127/204898311-096ec920-1138-4151-8727-204b30928690.png)

![image](https://user-images.githubusercontent.com/5235127/204898405-fcfc0728-81c7-4834-baa5-62e637a9ea89.png)

Any idea hwo to deal with this ?

**Comment by adriens** [comment]
target issue referenced : 

- https://github.com/tsl0922/ttyd/issues/1032

**Comment by naikrovek** [comment]
sounds like you will need to wait for homebrew to update their package.  My understanding is that they are pretty quick about this kind of thing.

**Comment by adriens** [comment]
> sounds like you will need to wait for homebrew to update their package. My understanding is that they are pretty quick about this kind of thing.

:crossed_fingers:

**Comment by maaslalani** [comment]
Hey @adriens, I have openend a PR on homebrew about this:

* https://github.com/Homebrew/homebrew-core/pull/116321

Looks like theres some issues holding back the merge.

To get around this use:

```
brew install --HEAD ttyd
```

**Comment by adriens** [comment]
Thanks a lot @maaslalani , here is the full command for the workaround : 

```
brew unlink ttyd
brew install --HEAD ttyd
vhs --version
# Run vhs command now ;-p
```

I can now prepare my gif :smile_cat:  :pray:

**Comment by adriens** [comment]
.... all is good except ....

:+1:  `webm`
:+1:  `mp4`
:-1: `gif` (because _it contains errors_)

![image](https://user-images.githubusercontent.com/5235127/204902166-c191f97d-6d7a-4f49-9a6c-ad96e2ff4be1.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/204903730-e9715133-974b-4df6-9541-7343eed900ed.png)

![image](https://user-images.githubusercontent.com/5235127/204903819-afe26002-6caa-46e0-bf6c-f17c5d88c987.png)

**Comment by mxcl** [comment]
I updated tea already, just saying. https://github.com/teaxyz/cli

```sh
$ sh <(curl tea.xyz) https://github.com/charmbracelet/vhs/blob/main/examples/demo.tape
```

**Comment by maaslalani** [comment]
ttyd is now 1.7.2 in brew!
