### ISSUE TITLE
Add `Set WorkingDirectory` setting

### ISSUE THREAD

**Issue by maaslalani** [charmbracelet/vhs#19]
VHS should have the ability to set the working directory of the the tape file so that it may be run from anywhere and produce the same result.

Proposed syntax:

```
Set WorkingDirectory $HOME/src/vhs/examples/glow
```

**Comment by tranzystorek-io** [comment]
Could there be a CLI flag for setting a starting directory?

**Comment by caarlos0** [comment]
I kinda like it, but at the same time I would be happy with an `Exec "cd ./dir"` or something like that...

**Comment by maaslalani** [comment]
Yeah I think you're right Carlos, this seems a bit unnecessary
