### ISSUE TITLE
Add Page Up and Page Down keys

### ISSUE THREAD

**Issue by mikelorant** [charmbracelet/vhs#203]
It would be beneficial to have the page up and page down keys as commands. This would be especially useful with the Bubbles list component which uses these keys to move pages.

Implemented with PR #202.

**Comment by mikelorant** [comment]
@maaslalani Any chance we can get the PR related to this issue merged?

Please take a look at my other issues for keys, Ive got implementations for them down already, just need some guidance before I submits PRs.

**Comment by maaslalani** [comment]
@mikelorant The PR looks great! I will merge tonight!

**Comment by mikelorant** [comment]
Thanks. The other 2 PRs require a fair bit more work. Ive got branches for both but Im not sure if my approach is right. Just let me how you'd like them implemented and I will do it the way you'd like.

**Comment by maaslalani** [comment]
Hey @mikelorant, the <kbd>Alt</kbd> + <kbd>Ctrl</kbd> modifiers should work well in combination with each other, see: https://github.com/charmbracelet/vhs/issues/33

**Comment by maaslalani** [comment]
The implementation will look something like:

```
Ctrl+Shift+O
Ctrl+Alt+L
Ctrl+Alt+Shift+P
Ctrl+Shift+Alt+C
```

Such that the modifiers can be combined (ideally in any order).

**Comment by mikelorant** [comment]
No problem. Knowing how alt works should make this much easier to implement.

**Comment by maaslalani** [comment]
Thanks again for the awesome work on this @mikelorant!
