### ISSUE TITLE
Add Shift Tab

### ISSUE THREAD

**Issue by mikelorant** [charmbracelet/vhs#204]
It would be beneficial to be able to use shift tab. Cycling between TUI components is often done with tab and shift tab, and this is currently not possible.

There is also some design issues that need to be resolved on how the command should work. There are two options:

1. `ShiftTab` to match the existing `Tab` command.
2. `Shift+TAB` to match the existing `Ctrl` command.

I currently have it implemented as `ShiftTab` in my local branch but unsure if this is the correct approach. Before I do the tests and make the commit PR worthy, I thought it best to create an issue to get some guidance.

**Comment by maaslalani** [comment]
Closing in favour of https://github.com/charmbracelet/vhs/issues/33
