### ISSUE TITLE
Add Alt modifier

### ISSUE THREAD

**Issue by mikelorant** [charmbracelet/vhs#205]
It would be beneficial to add the Alt key modifier to allow more control over applications. There are far more keyboard shortcuts possible using `Alt` than `Control` and many TUIs use this.

After investigating an implementation nearly identical to the control key, I discovered it was far more complicated because `go-rod` does not directly support this as a "key". These commands are not sent by pressing and releasing a modifier but with a prefix of the `Esc` sequence.

The important function is as follows:

```
const esc = '\x1b'

// ExecuteAlt is a CommandFunc that presses the argument key with the alt key
// held down on the running instance of vhs.
func ExecuteAlt(c Command, v *VHS) {
       for _, r := range c.Args {
               k := []rune{esc, unicode.ToLower(r)}
               _ = v.Page.InsertText(string(k))
       }
}
```

As you can see, I create a slice of runes with `Esc` being first and then add the lower case of the pressed key as the 2nd element. Lower case was necessary as using upper case is the equivalent of pressing `Alt` + `Shift` + key. I then convert the slices of runes back to a string and use `go-rod`'s `InsertText` method to send the entire escape sequence.

I wanted to confirm whether my approach to the implementation is the right before submitting the PR. In my own tests this has been working well.

There is one more issue I need clarification on. I also needed `Alt` + `Enter`. My approach was to allow `ENTER` as a key. My approach felt hacky and I think a better method might be possible.

```
const esc = '\x1b'
const enter = '\r'

// ExecuteAlt is a CommandFunc that presses the argument key with the alt key
// held down on the running instance of vhs.
func ExecuteAlt(c Command, v *VHS) {
	if c.Args == "ENTER" {
		c.Args = string(enter)
	}
	
	for _, r := range c.Args {
		k := []rune{esc, unicode.ToLower(r)}
		_ = v.Page.InsertText(string(k))
	}
}
```

I need some help before I submit the PR for this addition.

**Comment by maaslalani** [comment]
Closing in favour of https://github.com/charmbracelet/vhs/issues/33
