### ISSUE TITLE
Running `vhs` without arguments hangs unable to exit

### ISSUE THREAD

**Issue by mntlty** [charmbracelet/vhs#207]
Running 

```bash
$ vhs
```

on its own hangs waiting for input.

On OS X it does not responded to signals like CTRL+C to quit.

**Comment by rm-dr** [comment]
vhs isn't stuck, it's waiting for input from stdin.

If you run vhs with no arguments, it will wait for commands like a shell. Crtl-d should exit in this case.

This behavior isn't a bugm and allows us to `vhs < file.tape`. Many other tools work the same way! (try `cat` with no arguments)

It is a bit confusing, though.

**Comment by mntlty** [comment]
yup, understood what was happening after seeing the directions for `vhs < demo.tape`

ctrl+d does work, honestly I've forgotten that was a thing 😄 
would it be possible to have it exit on ctrl+c? I believe that's what most people would try to do

**Comment by mntlty** [comment]
> try cat with no arguments
cat does respect ctrl+c to exit:

```bash
$  cat            
^C
$
```

**Comment by mfigurski80** [comment]
I'm realizing that VHS doesn't respect ctrl-c however: accidentally set up a task with 100s wait times and there's no way to exit, had to kill the process. I'd absolutely love to take a look at this, if this is a bug you'd consider a PR for...

**Comment by maaslalani** [comment]
I think this is not the best UX, running `vhs` without any stdin or arguments should likely simply return the help. However, it is important to ensure that VHS still is able to process stdin if it is piped in.

I will fix this in the near future for the next release as it is slightly confusing for some!

**Comment by maaslalani** [comment]
This should be fixed by #215 now! Thanks for pointing this confusing behaviour out, @mntlty!
