### ISSUE TITLE
`Set Shell "bash -c 'jshell -R-ea'"` doesn't work

### ISSUE THREAD

**Issue by denkspuren** [charmbracelet/vhs#210]
`Set Shell "bash -c 'jshell -R-ea'"` doesn't work, unfortunately. I guess this is easy to fix, isn't it? :smirk:

**Comment by rm-dr** [comment]
First, please include more information when opening an issue. It is very hard to troubleshoot when all the information we're given is "X doesn't work." Include some versions, some error messages! Also list what you're trying to accomplish, there may be another way to do it.

Second, this isn't how `Set Shell` works. VHS only supports a few shells: bash, cmd, fish, powershell, and zsh.

If you want to record content inside of `jshell`, you'll need to call `jshell -R-ea` *inside* vhs with `Type "echo 'Welcome to VHS!'" Enter`

**Comment by caarlos0** [comment]
@rm-dr is correct, the `Set Shell` only allow a few predefined shells. If you want anything different, you'll have to use `Type`.

That being said, will close this.

Thanks!
