### ISSUE TITLE
Generated GIF contains only two f-word

### ISSUE THREAD

**Issue by j178** [charmbracelet/vhs#213]
Hi, I installed `vhs` through `brew install` on macOS, but all the tapes I tried would only generate a GIF with two f-word, like this:
![demo](https://user-images.githubusercontent.com/10510431/212381482-670a0909-7b5f-4023-82a3-b145d0f375f1.gif)

My steps:
```
vhs new demo.tape
vhs < demo.tape
```

Version information:
- macOS Monterey
- vhs 0.2.0
- ttyd 1.7.2

<details>
<summary>
ffmpeg
</summary>

```
ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers
built with Apple clang version 14.0.0 (clang-1400.0.29.202)
configuration: --prefix=/usr/local/Cellar/ffmpeg/5.1.2_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```

</details>

**Comment by bashbunni** [comment]
LOL 😂

**Comment by rm-dr** [comment]
Huh??

**Comment by j178** [comment]
Sorry, I don't kown why this is closed. This may sound like a joke, but it's actually happening to me…

https://user-images.githubusercontent.com/10510431/212520348-5c470c15-ccc4-485c-9326-308fff539638.mov

**Comment by rm-dr** [comment]
Not sure why you're wasting our time like this.
Please do not repeat this here or on any other repo.

**Comment by frostming** [comment]
> Not sure why you're wasting our time like this. Please do not repeat this here or on any other repo.

I don't see why you say it is a waste of time. The OP is a serious bug report, is there any obvious misuse or editing evidence in the video?

**Comment by j178** [comment]
@rm-dr I apologize for wasting your time, so sorry. 

After some digging myself, I find out that the "fuck fuck" is actually coming from `ttyd` (which, `vhs` relies on for recording terminal), here is a simple reproducing screenshot:

https://user-images.githubusercontent.com/10510431/212564671-67a15a99-c31b-458f-9230-58a468fe0763.mov

The "fuck fuck" text may appear due to the WebSocket connectin failure, but I don't have a clue why the WebSocket connection is closed. I'll keep digging deeper.

**Comment by Xuanwo** [comment]
> After some digging myself, I find out that the "fuck fuck" is actually coming from `ttyd` (which, `vhs` relies on for recording terminal), here is a simple reproducing screenshot:

After a quick review of `ttyd` & `libwebsocket` code, I didn't find clue that they could return f word. And it also doesn't make sense to fail on connect localhost.

Can you try disable the proxy (clash), and try again? I'm afraid some of traffic has been send to remote proxy server which doesn't support websocket upgrade.

**Comment by j178** [comment]
Thanks for your reply.

> I didn't find clue that they could return f word.

I'm confused too. I also searched codebase of `xterm.js`, did not find the source of f-word too.

> Can you try disable the proxy (clash), and try again? 

I tried actually, `clash` is not the root cause I think. 

If anyone is interested, here is the packets I captured using wireshark during the initial connecting:
[ttyd.zip](https://github.com/charmbracelet/vhs/files/10422370/ttyd.zip)

**Comment by rm-dr** [comment]
Is... Is this actually happening?
I can't think of an explanation, except for "malicious ttyd release" or "malicious issue author."

Whatever the case, I don't think this is a bug in VHS.

There's also a bit of a jump right after the file browser opens in the demo above, which raises a few eyebrows.

https://user-images.githubusercontent.com/10510431/212520348-5c470c15-ccc4-485c-9326-308fff539638.mov

**Comment by caarlos0** [comment]
is the possible OP has something in their bashrc that would print the f word in some cases... and forgot about it?

might also be some other software running when bash starts.

IMHO that's a bit more likely to happen than the alternatives...


fwiw if that's it, main should prevent it, as it won't load any rcs...

**Comment by yihong0618** [comment]
> Is... Is this actually happening? I can't think of an explanation, except for "malicious ttyd release" or "malicious issue author."
> 
> Whatever the case, I don't think this is a bug in VHS.
> 
> There's also a bit of a jump right after the file browser opens in the demo above, which raises a few eyebrows.
> 
>  Screen.Recording.2023-01-15.at.10.44.42.mov

Wouldn't it be better if VHS could avoid him at code level? 
IMO this is an interesting issue that other users may also encounter

**Comment by Xuanwo** [comment]
> Wouldn't it be better if VHS could avoid him at code level?

No, VHS couldn't do this and don't need to.

**Comment by yihong0618** [comment]
> > Wouldn't it be better if VHS could avoid him at code level?
> 
> No, VHS couldn't do this and don't need to.

copy that, thanks

**Comment by wey-gu** [comment]
I didn’t check how vhs works, but this reminds me of https://github.com/nvbn/thefuck, is it possible vhs will trigger the f word when it fails/returns none-zero(like WS upgrade,etc)?

**Comment by jw-12138** [comment]
https://twitter.com/niceoe/status/1664170529941749760?s=20

guess we found the reason

lmfao
