### ISSUE TITLE
Feature Request: Source command

### ISSUE THREAD

**Issue by bakks** [charmbracelet/vhs#220]
Some food for thought: I'd like to have a bunch of `.tape` files for a project I'm working on which share some configuration commands, e.g. terminal size, font size, theme, etc. It's pretty common with scripting systems to be able to include other scripts of the same type within the current script, i.e. a command which executes another script at the current line. So my proposal is that VHS adds a command called `Source`, which takes an argument of another script file, executes the content of that file, then continues on.

Here's an example:
common.tape
```
Set FontSize 18
Set Framerate 30
Set Padding 10
```

demo.tape
```
Output demo.gif
Source ./common.tape
Type "echo 'Welcome to VHS!'" Sleep 500ms  Enter  
Sleep 5s
```

The content from `common.tape` would be included on line 2, no other impacts.

Thoughts on this? Feel free to close this out if a bad idea, missing the point, or already possible 😃 .

**Comment by maaslalani** [comment]
Hey this is an awesome idea! This will definitely be implemented, I will close this since we are already tracking this in: #133.

**Comment by bakks** [comment]
Ahh missed that other ticket but yes it's the same idea. Thanks for following up here!
