### ISSUE TITLE
ttyd should only listen on localhost

### ISSUE THREAD

**Issue by rcw5** [charmbracelet/vhs#226]
The `ttyd` that VHS spins up listens on all interfaces. I've had a couple of occasions where `ttyd` has remained running after I killed VHS, which leaves an unauthenticated remote terminal open to my local network. 

Can `ttyd` be configured with the `--interface` flag so it only listens on 127.0.0.1? 

I'm happy to submit a small PR for this feature (modifying `tty.go`)

**Comment by maaslalani** [comment]
I believe this should be fine, since ttyd only needs to communicate with VHS locally. I do want to double check that the SSH server for VHS would still work to submit tapes over SSH but I think that it should be fine.

**Comment by rcw5** [comment]
Have submitted a PR. I wasn't able to test `vhs serve` as I couldn't get it working (not sure if something is missing from the documentation?) but was able to create a gif from a tape just fine

**Comment by maaslalani** [comment]
<img width="430" alt="image" src="https://user-images.githubusercontent.com/42545625/218870332-60787589-b885-4952-8cd7-3818c2440a61.png">


The default port may be the issue:

```
vhs serve
```

Then,

```
ssh localhost -p 1976 < demo.tape > demo.gif
```

**Comment by rcw5** [comment]
Got it - the issue happened because I mounted my repo inside the Docker container, so there was a file called `/vhs/vhs`, which is also where `VHS_KEY_PATH` points (https://github.com/charmbracelet/vhs/blob/main/Dockerfile#L54). My `/vhs/vhs` was not a key, hence the error :-). 

I was able to test `vhs serve` in Docker using container networking, will update the PR comments.

**Comment by taigrr** [comment]
Given the severity of this issue, could I request charm publish a new version hotfix release to incorporate this change please?

**Comment by bashbunni** [comment]
Will bring it up to the team and see how soon we can do a release 👀

**Comment by taigrr** [comment]
Hooray! this is fixed with latest release. Now I can install it :)

**Comment by maaslalani** [comment]
Awesome! Thanks for the patience @taigrr!
