### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by denis-akvelon** [charmbracelet/vhs#230]
I ran vhs via docker "sudo docker run --rm -v $PWD:/vhs ghcr.io/charmbracelet/vhs demo.tape".
In the demo.tape I have only one row: Type "git commit -m"  Sleep 500ms Enter.
The GIF file was created successfully, but the command was followed by an error: "bash: git: command not found."
I have no idea how to avoid it.
![test](https://user-images.githubusercontent.com/115065083/219608798-4ab45f10-33af-4bbd-8b80-f59006d22ae4.gif)

**Comment by bashbunni** [comment]
As mentioned in [this issue](https://github.com/charmbracelet/vhs/issues/14), it depends on the host to have the required software installed. In this case, you'll want to add Git to your Docker container. You should be able to add Git install instructions to your Dockerfile to build a Docker image that has Git installed. Running VHS from a container using that image would fix your problem!

**Comment by caarlos0** [comment]
correct @bashbunni! 
Thanks, closing!
