### ISSUE TITLE
panic: navigation failed: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by SimFG** [charmbracelet/vhs#233]
os: mac
install: `go install github.com/charmbracelet/vhs@latest`
run:
```
vhs new demo.tape

vhs < demo.tape
```

env:
```
vhs version v0.3.0
ttyd version 1.7.3
```

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/21985684/220911377-a9c1d8b7-1585-49f7-b5f7-22e219a74bdd.png">

**Comment by caarlos0** [comment]
running on wsl by any chance?

if not, please try

```
go install github.com/charmbracelet/vhs@main
```

and try again... errors handling is a bit better, might give a hint on the cause

**Comment by SimFG** [comment]
![image](https://user-images.githubusercontent.com/21985684/221074713-926aabfb-cf68-4e5d-809a-5136c952838b.png)

**Comment by taigrr** [comment]
on macos Ventura, I cannot reproduce. Using same ttyd release as OP and vhs@main. Example gif generates correctly.

**Comment by SimFG** [comment]
i succeeded. and it need `sudo`, but I don't know why
![image](https://user-images.githubusercontent.com/21985684/221082289-ef66eedb-ce4d-47f9-b3c5-796b253d21ac.png)

**Comment by taigrr** [comment]
Oh, it might have been for network permission rules. I did see a pop-up briefly flash on my screen but it was quick enough to be unreadable. 

Do you have tighter-than-default network security settings configured on your mac? Anything that might prevent port binding by default? Little Snitch installed? Etc

**Comment by michalrudowicz** [comment]
Hi,

I have the same (or similar) looking issue on openSUSE Tumbleweed. `sudo` doesn't help. From what I see it is caused by `ttyd` failing to start correctly - after running `ttyd` manually I get an error informing me about the lack of libraries:

```
[2023/03/03 07:31:48:1033] E: lws_create_context: failed to load evlib_uv
[2023/03/03 07:31:48:1033] E: libwebsockets context creation failed
```

I assume that this is a packaging error unrelated to VHS. I don't have a solution to that yet, and I don't know if that's the same issue as originally, but my conclusion is: check if `ttyd` works without vhs, and check its error messages if it doesn't.

**Comment by raguay** [comment]
I have the same error, but `sudo` doesn't help and my security is very standard. I'm on the macOS Ventura 13.5 (22G74) (the update to 13.5 was just today). I'm on a MacBook Pro M1 system and I installled vhs using homebrew.

**Comment by raguay** [comment]
Nope. It give:

ttyd bash
[2023/07/26 20:50:56:5231] N: ttyd 1.7.3-a8cae75 (libwebsockets 4.3.2-unknown)
[2023/07/26 20:50:56:5235] N: tty configuration:
[2023/07/26 20:50:56:5235] N:   start command: bash
[2023/07/26 20:50:56:5235] N:   close signal: SIGHUP (1)
[2023/07/26 20:50:56:5235] N:   terminal type: xterm-256color
[2023/07/26 20:50:56:5239] E: Scandir on '/opt/homebrew/Cellar/libwebsockets/4.3.2/lib' failed, errno 2
[2023/07/26 20:50:56:5240] E: lws_create_context: failed to load evlib_uv
[2023/07/26 20:50:56:5240] E: libwebsockets context creation failed

That should be a native app, right? Why the reference to a homebrew directory?

**Comment by raguay** [comment]
Okay. I reinstalled ttyd from homebrew and it now works. You might add a note about that error message with this way to fix it.

**Comment by caarlos0** [comment]
> That should be a native app, right? Why the reference to a homebrew directory?

ttyd is not native, no...

that said, I don't know why it doesn't work... does `/opt/homebrew/Cellar/libwebsockets/4.3.2/lib` exist?

**Comment by raguay** [comment]
> Okay. I reinstalled ttyd from homebrew and it now works. You might add a note about that error message with this way to fix it.

I found out that it was a homebrew command and re-installed it. It now works fine.

**Comment by raguay** [comment]
> > That should be a native app, right? Why the reference to a homebrew directory?
> 
> ttyd is not native, no...
> 
> that said, I don't know why it doesn't work... does `/opt/homebrew/Cellar/libwebsockets/4.3.2/lib` exist?

I found out that it was a homebrew command, but I didn't remember ever installing it. I re-installed it from homebrew and it now works. It must of gotten messed up at some point. I committed about it at about the same time you did!

**Comment by caarlos0** [comment]
glad you figured it out :D
