### ISSUE TITLE
Cannot get VHS to capture entire screen

### ISSUE THREAD

**Issue by tpryan** [charmbracelet/vhs#235]
I cannot get VHS to capture my whole app screen. I'm sure I'm doing something stupid here but I just can't figure it out. 

I have a TUI that I wrote using Bubbletea, and when I run vhs I get this: 
 
![demo](https://user-images.githubusercontent.com/211495/220987184-399afa06-270c-4f66-871c-3d2290024709.gif)

In contrast it should look more like this: 

![ui_choose_project](https://user-images.githubusercontent.com/211495/220987278-d0e8155b-e711-498a-b7d1-778f2d17d1f8.gif)

I have tried a bunch of things to try and change the behavior here:

* Fiddled with Height, Width, Frame Rate
* Tried spinning it up on another OS
* Turning off tea.WithAltScreen
* Deactivated the Escape codes I emit in my app. 

I'm wracking my brains here.  Can anyone point me in the right direction?

**Comment by maaslalani** [comment]
Hey, can you set the margin to 0 and decrease the font size?

```
Set Margin 0 # or whatever you want (default is 60)
Set FontSize 12
```

That should help capture more of the screen, but you can also set the height and width:

```
Set Height 1200
Set Width 2000
```

**Comment by tpryan** [comment]
It didn't like Margin (said it wasn't a valid setting)
But it looks like setting the font size did the trick. 

THANK YOU!

**Comment by maaslalani** [comment]
No problem! Thanks for using VHS ❤️
