### ISSUE TITLE
unexpected output at start of GIF

### ISSUE THREAD

**Issue by kfaizi** [charmbracelet/vhs#243]
When feeding the demo.tape file through VHS with no modifications, I got the following output:

![demo](https://user-images.githubusercontent.com/30393862/222029856-e5c30b12-70eb-4373-8773-4e069f96c164.gif)

If you look closely, the first few frames (before and while `echo` is typed) are cluttered with some unexpected text:
```
set +o history; unset PROMPT_COMMAND; export PS1="\[\e[38;2;90;86;224m\]> \[\e[0m\]"; clear;
```
Seems like VHS is styling the prompt before making the GIF, but not sure why this would show up in the final product.

**Comment by maaslalani** [comment]
Hey @tuxiqae @kfaizi, is this still an issue in `v0.4.0` for you?

**Comment by tuxiqae** [comment]
Seems like it works for me
```
⤅ vhs --version
vhs version v0.4.0 (5409c97)
```

**Comment by maaslalani** [comment]
Awesome! Will close this issue, feel free to reopen if it's not fixed for you @kfaizi

**Comment by kfaizi** [comment]
sorry for the slow reply -- this fixed it for me too! thanks a bunch <3
