### ISSUE TITLE
gum confirm isn't displayed correctly

### ISSUE THREAD

**Issue by basilioss** [charmbracelet/vhs#256]
Here is the `test.tape`:
```
Require gum
Type 'gum confirm && echo "yes" || echo "no"'
Enter
Sleep 3s
Right
Sleep 1s
Left
Sleep 1s
Enter
Sleep 3s
```

Here is the output gif:

![out](https://user-images.githubusercontent.com/71596800/224506491-4ab389c4-2a2d-4e3c-9339-31e9f21d9751.gif)

gum version: 0.9.0 (832c4fc)
vhs: v0.2.0 (6f7cc81)
bash: 5.1.16(1)-release
OS: Arch Linux

Note that I don't have `.bashrc` and there is the same problem with zsh while recording gum with vhs.

I tried to install 0.3.0 version from AUR but it has the same issue.

**Comment by StarpTech** [comment]
Seems related #282

**Comment by maaslalani** [comment]
Hey! this should be fixed if you use `vhs@main` and `ttyd@main`:

```bash
go install github.com/charmbracelet/vhs@main
```

```bash
brew install ttyd --HEAD
```

![out](https://github.com/charmbracelet/vhs/assets/42545625/6edd5e82-399c-4db7-9535-6dd4578d8260)

Thank you so much for reporting this issue!
