### ISSUE TITLE
The '<' operator is reserved for future use.

### ISSUE THREAD

**Issue by dqmn** [charmbracelet/vhs#266]
Powershell: 
```
At line:1 char:5
+ vhs < test.tape
+     ~
The '<' operator is reserved for future use.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RedirectionNotSupported
```
I know there is an option to use another terminal like the old windows command line, git bash, tabby, cmder etc. but I suggest making a command instead of feeding it into VHS.

**Comment by maaslalani** [comment]
You should be able to also pass the file name as an argument.

```bash
vhs test.tape
```

Let us know if that doesn't work for you.

**Comment by stjohnfinn** [comment]
Is this advertised somewhere in the readme? I am unable to find it and I think it would be extremely helpful for Windows users.
