### ISSUE TITLE
Alt+Enter issues

### ISSUE THREAD

**Issue by jedahan** [charmbracelet/vhs#292]
![alt-enter-issue](https://user-images.githubusercontent.com/32407/232545351-c0387d46-459c-47c8-be88-04adcba9279c.gif)

```tape
Output alt-enter.gif

Type 'echo hello vhs' Sleep 0.5 Alt+Enter
Type 'second line' Sleep 0.5 Enter
```

**Comment by bashbunni** [comment]
Hey, it looks like this is a known issue. Here's what the author said:
> Hey, at the moment only Alt+<Character> are supported i.e. Alt+L etc...
We will definitely add support for Alt+Enter Alt+Backspace, etc... in the future

**Comment by maaslalani** [comment]
Hey @jedahan,

This will allow `Alt+Enter` to be used: https://github.com/charmbracelet/vhs/pull/305
