### ISSUE TITLE
vhs freeze with mason search

### ISSUE THREAD

**Issue by IGLOU-EU** [charmbracelet/vhs#303]
Hi :wave: 

**Describe the bug**
I try to make a vim GIF to show a mason search.
But at the mason step vhc stuck.

**Setup**
Please complete the following information along with version numbers, if applicable.
 - RchLinux (btw)
 - GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
 - kitty 0.28.1 created by Kovid Goyal
 - tmux 3.3_a-3

**To Reproduce**
[nvchad.txt](https://github.com/charmbracelet/vhs/files/11453895/nvchad.txt)

**Comment by bashbunni** [comment]
Hi @IGLOU-EU I wasn't able to reproduce this issue. Could you please provide steps to reproduce? Also, are you using Vim or Neovim? It would be great if you could show the output of the vhs recording in this issue, ideally not in a file we would need to download. Thank you :)

**Comment by bashbunni** [comment]
Hey @IGLOU-EU just following up on this. Is this still an issue for you? If so, can you please provide steps to reproduce? Otherwise I'll have to close the issue. Let us know :)

**Comment by IGLOU-EU** [comment]
Hi @bashbunni, I didn't have time to think about it. I promise I'll try again by the end of the month 😓

**Comment by bashbunni** [comment]
Sounds good, thank you!

**Comment by IGLOU-EU** [comment]
I had a problem with a lib for nvim chad. The goal was to show this problem, but it was probably causing unpredictable behavior.   
I can't reproduce the bug anymore... :crying_cat_face: 

I'm so sorry :(

**Comment by bashbunni** [comment]
No problem! @IGLOU-EU thanks for the update, glad you're not experiencing these issues anymore :)
