### ISSUE TITLE
release asset names & scoop bucket

### ISSUE THREAD

**Issue by PizzaKirby** [charmbracelet/vhs#309]
**Describe the bug**
I had noticed that scoop failed to find the recent 0.5.0 update.
This seems to be the case since because the Windows (and other) release archives no longer contain the version number in their name.
Was this an intended change or an oversight ?

**Comment by caarlos0** [comment]
what do you mean scoop failed to find? can you paste the error? Looking here, although the filenames change, everything seems fine...

also, are you using our scoop bucket or something else?

**Comment by PizzaKirby** [comment]
Sorry for the confusing choice of words.
I'm using the main scoop bucket.
Basically it fails to recognize there is a newer version available

```
❯ scoop update vhs
vhs: 0.4.0 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
```

I suspected it was due to the autoupdate section in the manifest requiring a version to be present in the name
```json
"autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/charmbracelet/vhs/releases/download/v$version/vhs_$version_Windows_x86_64.zip"
            },
            "32bit": {
                "url": "https://github.com/charmbracelet/vhs/releases/download/v$version/vhs_$version_Windows_i386.zip"
            }
        },
        "hash": {
            "url": "$baseurl/checksums.txt",
            "regex": "(?m)^$sha256.*?$basename$"
        }
    }
```

**Comment by caarlos0** [comment]
Here you go: https://github.com/ScoopInstaller/Main/pull/4818

Thanks again for reporting this!

**Comment by PizzaKirby** [comment]
Thank you for the quick response!
Also I had no idea you have your own scoop bucket since it's not mentioned anywhere in the install instructions 👍
