### ISSUE TITLE
Interactive Tape Writing

### ISSUE THREAD

**Issue by maaslalani** [charmbracelet/vhs#32]
VHS should have an interactive mode for writing tape files which would look something like:

```
vhs record
```

Which would open up a browser terminal and listen to your browser events and write to a tape file. This would make it much easier to write tape files but still keep them easily editable for modifications and tweaks for the final render.

**Comment by paralin** [comment]
Open a browser tab - would that be better / easier to implement than running a shell as a subprocess and forwarding stdio to the user?

**Comment by maaslalani** [comment]
Yeah thinking about it more we'll probably end up just writing a CLI/TUI that listens to keypress to keep it more lightweight.

**Comment by gmatev** [comment]
Indeed the ability to capture a terminal session to seed the tape file would be huge. Especially useful, if you are trying to record something that has more sophisticated interactions like animations done using ASCI cursor control sequences.

**Comment by maaslalani** [comment]
@paralin @gmatev I have a working prototype at #135 if you want to give it a go!

**Comment by paralin** [comment]
Now we have `vhs record` and https://github.com/rsteube/cast2tape - nice!
