### ISSUE TITLE
`Alt` + `Shift` modifiers

### ISSUE THREAD

**Issue by maaslalani** [charmbracelet/vhs#33]
VHS should support `Alt` and `Shift` modifiers for keypress:

```
Ctrl+Shift+O
Ctrl+Alt+L
Ctrl+Alt+Shift+P
Ctrl+Shift+Alt+C
```

**Comment by abenson** [comment]
Function keys, as well.

**Comment by Airblader** [comment]
Is there any workaround? This is pretty crucial for some things.

**Comment by kdheepak** [comment]
Hi all. Thanks for making this tool, it has been amazingly useful to create short gif demos on command line functionality.

It doesn't seem possible to press a function key at the moment. Is that something that could be added?
