### ISSUE TITLE
VHS fails to render background color changes on whitespace.

### ISSUE THREAD

**Issue by joshka** [charmbracelet/vhs#344]
**Describe the bug**
I'm trying to capture demos for [Ratatui](https://github.com/tui-rs-revival/ratatui) (a rust tui crate) and I'm seeing some discrepancy between what the terminal sees, what ttyd sees and what vhs captures. Particularly this is visible with backgrounds. https://github.com/tui-rs-revival/ratatui/pull/303 is an issue that highlights some of the problem.

**Setup**
Please complete the following information along with version numbers, if applicable.
 - macOS
 - zsh
 - iterm
 - none

**To Reproduce**
Steps to reproduce the behavior (on a machine with rust installed)
1. git clone https://github.com/joshka/ratatui.git --branch=docs-examples
2. cd ratatui
3. cargo run --example=gauge
4. vhs examples/gauge.tape
5. `ttyd --interface 127.0.0.1 --port 11122 -t renderType=canvas -t disableResizeOverlay=true -t enableSixel=true -t customGlyphs=true --once zsh` and then `cargo run --example=gauge` at http://localhost:11122

**Source Code**
Please include source code if needed to reproduce the behavior. 
```
 This is a vhs script. See https://github.com/charmbracelet/vhs for more info.
# To run this script, install vhs and run `vhs ./examples/gauge.tape`
Output "target/gauge.gif"
Set Width 1200
Set Height 600
Hide
Type "cargo run --example=gauge --features=crossterm"
Enter
Sleep 1s
Show
Sleep 20s
```

**Expected behavior**

**Screenshots**
iterm view:
<img width="645" alt="image" src="https://github.com/charmbracelet/vhs/assets/381361/91319b21-7787-456e-acb4-345005cf702d">

vhs gif:
![gauge](https://github.com/charmbracelet/vhs/assets/381361/fb8f1823-565b-4e20-a846-ea7ff0467958)

ttyd (in firefox):
<img width="435" alt="image" src="https://github.com/charmbracelet/vhs/assets/381361/ef27fcb4-0d5f-4cd4-91c3-286c7247ac02">

**Additional context**
Our popup example has a similar issue (and several other examples did, but some changes have avoided the issue).
![popup](https://camo.githubusercontent.com/a49463480841a3d917d3489318ebef6ea0034230457634f1378fccd3c3198683/68747470733a2f2f7668732e636861726d2e73682f7668732d477a307a766c424a616c4c433358744830594370462e676966)
It seems like something is not quite capturing the start / end of the set background commands correctly.
I haven't done a minimal repro for this, but have at least narrowed the place the issue could be I hope.

**Comment by hasezoey** [comment]
easy VHS repro:

```vhs
Output bleed.gif
Set Width 500
Set Height 500
Set Shell zsh
Set TypingSpeed 1ms
Type "printf 'Test \033[0;31mTest\033[0;60m Test\033[0m           '"
Sleep 2s
Enter

Type "printf 'Test \033[0;31mTest\033[0;103m Test\033[0m          '"
Sleep 2s
Enter

Sleep 2s
```

renders:
![bleed](https://github.com/charmbracelet/vhs/assets/10911626/35ebeaf4-aecd-46a5-a4dd-983e8bad5dac)

but in Konsole (zsh) it renders as:
![Screenshot_20230812_170553](https://github.com/charmbracelet/vhs/assets/10911626/99e4fce9-a0a4-49e6-9a36-3562120ccb8e)

**Comment by joshka** [comment]
Installing the source version of ttyd which contains an updated xterm.js fixes the issue.
On a mac: `brew install ttyd --HEAD`

![bleed](https://github.com/charmbracelet/vhs/assets/381361/44ffbc4a-9982-40b6-b9b5-f83fa40e329c)

This is a duplicate of #249 (and several other issues) but I'd suggest to leave this or some other issue open until ttyd is updated (I've made a request for a release in https://github.com/tsl0922/ttyd/issues/1201).

**Comment by joshka** [comment]
The upstream is updated now - which should make it possible to use the release version rather than the head version.
