### ISSUE TITLE
[Docs] mention how to escape characters in `Type`

### ISSUE THREAD

**Issue by hasezoey** [charmbracelet/vhs#356]
Currently i cannot find any documentation on how characters in `Type` could be escaped, for example escaping `"`, where i already tried `\"` but it says invalid character

if it should be added, it should maybe be added to [this section](https://github.com/charmbracelet/vhs#type)

example:
```vhs
# unescaped, error
Type "echo "Test""

# trying to escape, also error
Type "echo \"Test\""

# changing to single quotes works
Type "echo 'Test'"
```

**Comment by jskulski** [comment]
I am trying to use vhs with an environment variable and not finding it straightforward. So agree that adding something to the docs about escaping would be very helpful. I'll post here if I figure it out.

**Comment by alexwforsythe** [comment]
FYI support for backticks was added in #157, so you don't need to escape quotes if you use them:

```sh
Type `echo "$MY_ENV_VAR"`
Type `echo "I can even use 'mixed quotes'"`
```

**Comment by maaslalani** [comment]
Thanks so much for the issue @hasezoey

Fixed by https://github.com/charmbracelet/vhs/pull/429#

**Comment by hasezoey** [comment]
just to confirm, this means the still is not "proper" escaping support? (ie using the character that starts the string within the string)
