### ISSUE TITLE
Escape sequences not coloring white-space characters

### ISSUE THREAD

**Issue by jakehamilton** [charmbracelet/vhs#361]
**Describe the bug**

Attempting to print out text that only contains color escape sequences and white-space results in completely blank output.

**Setup**
 - OS: NixOS
 - Shell: ZSH
 - Terminal Emulator: Foot
 - Terminal Multiplexer: tmux

^ This occurs regardless of where `vhs` is run. This has happened within a systemd service's script as well as reproducing it manually.

**To Reproduce**
1. Download [`cow.txt`](https://github.com/charmbracelet/vhs/files/12331810/cow.txt) or create a file with escape sequences and white-space.
2. Create a tape that prints out the contents of the file.

```tape
Output frames

Hide
Type "export PS1=''" Enter
Type "clear && cat ./cow" Enter
Show

Sleep 1
```

4. Open the resulting frame: `xdg-open ./frames/frame-text-00001.png`
5. Colored spaces are not displayed :(

**Source Code**

This occurs when updating [@snowfallorg/cowsay](https://github.com/snowfallorg/cowsay/) from `nixos-22.11` to `nixos-23.05`.

To see it working with `nixos-22.11`:

```
nix run .#cow2img
xdg-open ./cow/image.png
```

To see it broken with 23.05:

```
# Change nixos-22.11 to nixos-23.05 in the flake's inputs.
$EDITOR flake.nix

nix run .#cow2img
xdg-open ./cow/image.png
```

**Expected behavior**

Colored white-space should be displayed similar to how it was before this bug appeared.

**Screenshots**

Poor [@cowsay](https://hachyderm.io/@cowsay) bot posted some broken images before going on hiatus:

- https://hachyderm.io/@cowsay/110886063539235194
- https://hachyderm.io/@cowsay/110600259103949960
- https://hachyderm.io/@cowsay/110594597196012674

**Additional context**

I don't _think_ this is an issue with `xterm.js` since I can't reproduce the issue by manually printing out the file (not using VHS) on Replit. Open [this Repl](https://replit.com/@jakehamiltondev/VHS-Cow-Bug-Reproduction-Attempt?v=1) and click Run. This executes `cat ./cow` to print the file using `xterm.js`.

**Comment by maaslalani** [comment]
Thanks for this well written issue and documented reproduction steps + details. I really appreciate it. I will try to get this fixed!

**Comment by joshka** [comment]
I think this might be the same issue as https://github.com/charmbracelet/vhs/issues/344

**Comment by joshka** [comment]
Try installing the latest version of ttyd from source - that fixed my similar issue
- https://github.com/tsl0922/ttyd/issues/1201 is a request for a new release.

**Comment by jakehamilton** [comment]
I can confirm that this issue is now fixed on `nixos-unstable`! The issue persists on `23.05`, but this is easy enough for me to work around!

**Comment by maaslalani** [comment]
Thanks for confirming @jakehamilton!
