### ISSUE TITLE
VHS Not Showing Bubble Tea Program Correctly

### ISSUE THREAD

**Issue by seanbanko** [charmbracelet/vhs#362]
Creating an issue here to track a question originally asked on Discord as requested by @bashbunni :

I'm trying to use VHS to record a gif of a project that I built with Bubble Tea and Lip Gloss, but I've run into two different problems.

In the first case, the gif output by VHS looks different (and broken) compared to what it looks like when I run the program locally. My program has some text is styled with Lip Gloss to have a background color (in one place just text, in another place it is the titles of some List bubbles), and in the gif output the background color continues to extend to the right as far as it can.

My terminal:
<img width="1205" alt="Screenshot 2023-08-17 at 7 39 41 PM" src="https://github.com/charmbracelet/lipgloss/assets/74473367/e120c32a-407e-4a71-98bd-e25b55cc5358">

VHS:
<img width="1205" alt="Screenshot 2023-08-17 at 7 38 51 PM" src="https://github.com/charmbracelet/vhs/assets/74473367/0413dcfc-697e-4e5c-b385-0d9dc8fed694">

In the second case, when I tried to remove the auth flow so that I could create a reproducible example for this issue, I found that VHS stopped showing my Bubble Tea program even start at all (despite a 5 second pause to wait):

My terminal:
<img width="1411" alt="Screenshot 2023-08-17 at 8 09 28 PM" src="https://github.com/charmbracelet/vhs/assets/74473367/94a194e2-df98-4ccf-97b2-4fd496de7ba4">

VHS:
<img width="1205" alt="Screenshot 2023-08-17 at 8 09 09 PM" src="https://github.com/charmbracelet/vhs/assets/74473367/9ad22381-5a4a-4029-9372-b85f009afead">

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS: macOS Ventura 13.5.1
 - Shell: zsh 5.9
 - Terminal Emulator: kitty 0.28.1
 - Locale: en_US.UTF-8

**To Reproduce**
The project isn't quite finished and currently includes an allow-list-only Google sign-in authorization flow. I've tried to remove that flow, but then instead of VHS displaying a broken output, n

**Source Code**
https://github.com/seanbanko/gocal
dev branch produces the gif with broken background styling, issue branch produces the gif where nothing appears at all.

**Expected behavior**
The gif output by VHS should match what I see in my terminal.

**Comment by joshka** [comment]
This looks like the same issue as https://github.com/charmbracelet/vhs/issues/344 (and possibly https://github.com/charmbracelet/vhs/issues/361)

**Comment by joshka** [comment]
Try installing the latest version of ttyd from source - that fixed my similar issue
- https://github.com/tsl0922/ttyd/issues/1201 is a request for a new release.

**Comment by seanbanko** [comment]
@joshka worked like a charm. Thank you. I'll close this.

**Comment by joshka** [comment]
The upstream is updated now - which should make it possible to use the release version rather than the head version.
