### ISSUE TITLE
Background color stretches to EOL

### ISSUE THREAD

**Issue by antonmedv** [charmbracelet/vhs#365]
**Describe the bug**

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS: macos m2
 - Shell: zsh
 - Terminal Emulator: terminal.app
 - Terminal Multiplexer: none

**To Reproduce**
- Try to record https://github.com/antonmedv/walk
- Top bar stretches the whole line, but it should not.

**Screenshots**
VHS:
![](https://github.com/antonmedv/walk/raw/master/.github/images/demo.gif)

Screenshot:
<img width="922" alt="Screenshot 2023-08-21 at 18 19 30" src="https://github.com/charmbracelet/vhs/assets/141232/4fcee7f1-508b-4be3-b743-e671d15941a6">

Thanks for the awesome VHS! ❤️

**Comment by maaslalani** [comment]
Hey @antonmedv what version of TTYD are you using? This is a known solved bug!

**Comment by maaslalani** [comment]
https://github.com/charmbracelet/vhs/issues/282

**Comment by antonmedv** [comment]
I'm using 
```
 ❯ ttyd -v
ttyd version 1.7.3
```

**Comment by antonmedv** [comment]
```
brew unlink ttyd
brew install ttyd --HEAD
```
 
Helped. Thanks!

**Comment by maaslalani** [comment]
Awesome! Thanks for using VHS!

**Comment by joshka** [comment]
The upstream is updated now - which should make it possible to use the release version rather than the head version.
