### ISSUE TITLE
`Copy` + `Paste` commands

### ISSUE THREAD

**Issue by maaslalani** [charmbracelet/vhs#368]
VHS should allow for accessing and writing to the clipboard.

```elixir
Copy "https://github.com/charmbracelet"
Type "open "
Sleep 500ms
Paste
```

There are not really any security concerns since VHS is already very privileged and can access the clipboard through <kbd>ctrl+v</kbd> anyway.

---

### Alternative / Workaround

Currently you can simply use `Hide` / `Show` to simulate a pasting action.

```elixir
Type 'open '
Sleep 500ms
Hide
  Type "https://github.com/charmbracelet"
Show
```

**Comment by Delta456** [comment]
I am interested in working on this issue.

**Comment by maaslalani** [comment]
Hey @Delta456, awesome! I can assign this to you. Let me know if you need any more clarification or pointers.
