### ISSUE TITLE
Package not available in Nixpkgs?

### ISSUE THREAD

**Issue by montchr** [charmbracelet/vhs#41]
I tried to install `vhs` following the instructions for Nix, however the package does not appear to be available in Nixpkgs, even with a full repo/issues/PR search.

https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Aupdated-desc+vhs+

**Comment by maaslalani** [comment]
Apologies for that, we haven't added it to nixpkgs yet! I will make a PR soon!

**Comment by maaslalani** [comment]
PR is here (draft): https://github.com/NixOS/nixpkgs/pull/198112

**Comment by muesli** [comment]
Merged upstream!
