### ISSUE TITLE
Request: Release 0.7.0 and more regularly

### ISSUE THREAD

**Issue by joshka** [charmbracelet/vhs#416]
**Is your feature request related to a problem? Please describe.**
I have a project that relies on the themes and screenshot command changes that wer added since the last release (0.6.0 July 20). It's frustrating not to have this in a release version and have to add instructions on installing go in order to use the latest version of VHS installed from main.

**Describe the solution you'd like**
Please release more regularly. Perhaps automate the release process so that it happens more often?

**Describe alternatives you've considered**

**Additional context**
We use VHS to document [Ratatui](https://ratatui.rs) a Rust TUI framework.

**Comment by maaslalani** [comment]
Hey! @joshka, `0.7.0` has just been released! Thanks for your patience and reminder! ❤️

**Comment by amanibhavam** [comment]
@maaslalani The `0.7.0` release is missing binary assets

**Comment by maaslalani** [comment]
Great catch @amanibhavam, apologies for that! Made a 0.7.1 which contains the binary assets.

**Comment by joshka** [comment]
Nice! Thanks!
