### ISSUE TITLE
issue: `vhs` thinking that I am running on `WSL` when it is not the case

### ISSUE THREAD

**Issue by Delta456** [charmbracelet/vhs#44]
I have downloaded `vhs` from [GitHub Release](https://github.com/charmbracelet/vhs/releases/download/v0.1.0/vhs_0.1.0_Windows_x86_64.zip).  I am trying to make some GIF for my examples of the project [box-cli-maker](https://github.com/Delta456/box-cli-maker) with the following code:

```
# Where should we write the GIF?
Output demo.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 46
Set Width 1200
Set Height 600

# Type a command in the terminal.
Type "go run path\git\box-cli-maker\examples\unicode.go"

# Pause for dramatic effect...
Sleep 500ms

# Run the command by pressing enter.
Enter

# Admire the output for a bit.
Sleep 5s
```

The GIF successfully produces but it throws me an error as it expects `go` to be installed on **Ubuntu** when I am not running `vhs` on WSL.

![demo](https://user-images.githubusercontent.com/28479139/198361431-7b7672e1-3c73-4c17-ad61-b6f39bc7c887.gif)

It seems weird to me how this happened 🤔

**Comment by griimick** [comment]
- This issue is for the Windows environment _outside_ WSL

The default shell currently is `bash` which invokes WSL in Windows. Try executing `bash` or `ttyd bash` in psh or cmd in Windows 10/11.

I think this will get fixed once we have support setting different shells. Maybe default to powershell or cmd for Windows. Possible relation to #47.

**Comment by caarlos0** [comment]
on that sense, https://github.com/charmbracelet/vhs/pull/55 should fix it, adding support for setting any custom shell, as well as defaults for `pwsh`, `fish`, `zsh` and `bash`.

**Comment by maaslalani** [comment]
As Carlos mentioned #55 will fix this issue!

**Comment by Delta456** [comment]
Shouldn't this issue be open until it is completed?

**Comment by maaslalani** [comment]
This issue https://github.com/charmbracelet/vhs/issues/47 tracks the set shell feature so we'll keep that one open until we merge the PR
