### ISSUE TITLE
panic: [launcher] Failed to launch the browser

### ISSUE THREAD

**Issue by DannyBen** [charmbracelet/vhs#45]
Does this require a browser to function?...

Running the below commands on Ubuntu 20 (headless), ttyd 1.7.2, I get the error below.

```
$ vhs new demo.tape
$ vhs < demo.tape
```

### Output

```
panic: [launcher] Failed to launch the browser, the doc might help https://go-rod.github.io/#/compatibility?id=os: /home/vagrant/.cache/rod/browser/chromium-1033860/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory


goroutine 1 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0xd784e0?, 0xc00008d8a0?})
	/home/runner/go/pkg/mod/github.com/go-rod/rod@v0.112.0/lib/utils/utils.go:60 +0x25
github.com/go-rod/rod/lib/utils.E(...)
	/home/runner/go/pkg/mod/github.com/go-rod/rod@v0.112.0/lib/utils/utils.go:66
github.com/go-rod/rod/lib/launcher.(*Launcher).MustLaunch(0xc000189730?)
	/home/runner/go/pkg/mod/github.com/go-rod/rod@v0.112.0/lib/launcher/launcher.go:351 +0x67
main.New()
	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.0/vhs.go:65 +0x22a
main.Evaluate({0xc000490900, 0x85b}, {0x1449ac0, 0xc000012018}, {0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.0/evaluator.go:30 +0x1c5
main.glob..func1(0x1a0c340?, {0x1a60598, 0x0, 0x0?})
	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.0/main.go:61 +0x16a
github.com/spf13/cobra.(*Command).execute(0x1a0c340, {0xc000022070, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x1a0c340)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
main.main()
	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.0/main.go:136 +0x25
```

**Comment by muesli** [comment]
We should try to avoid the panic and add it to the deps: you will probably have to install `libgbm1` on Ubuntu.

**Comment by DannyBen** [comment]
> you will probably have to install `libgbm1` on Ubuntu.

Magnificent! After a quick `sudo apt install libgbm1` - it works like a charm_

I am assuming this dependency be bundled in the 0.1.1 .deb?

**Comment by UtahDave** [comment]
I ran `apt install libgbm1` and it was already installed. I'm still getting the same error as above.

Ubuntu 22.04 headless

**Comment by muesli** [comment]
> I ran `apt install libgbm1` and it was already installed. I'm still getting the same error as above.

Just to be certain it's the exact same error, can you paste your output?

**Comment by UtahDave** [comment]
```
root@idemvhs:~/vhsstuff# vhs < idem.tape 
panic: [launcher] Failed to launch the browser, the doc might help https://go-rod.github.io/#/compatibility?id=os: /root/.cache/rod/browser/chromium-1033860/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


goroutine 1 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0xd80b20?, 0xc0004478b0?})
	/home/runner/go/pkg/mod/github.com/go-rod/rod@v0.112.0/lib/utils/utils.go:60 +0x25
github.com/go-rod/rod/lib/utils.E(...)
	/home/runner/go/pkg/mod/github.com/go-rod/rod@v0.112.0/lib/utils/utils.go:66
github.com/go-rod/rod/lib/launcher.(*Launcher).MustLaunch(0xc00011c690?)
	/home/runner/go/pkg/mod/github.com/go-rod/rod@v0.112.0/lib/launcher/launcher.go:351 +0x67
main.New()
	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.1/vhs.go:67 +0x27b
main.Evaluate({0xc0004b8900, 0x864}, {0x1454480, 0xc000012018}, {0x0, 0x0, 0x0?})
	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.1/evaluator.go:33 +0x1c5
main.glob..func1(0x1a1b320?, {0x1a6f590, 0x0, 0x0?})
	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.1/main.go:60 +0x16d
github.com/spf13/cobra.(*Command).execute(0x1a1b320, {0xc000022230, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x1a1b320)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
main.main()
	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.1/main.go:135 +0x25
```

**Comment by UtahDave** [comment]
OK, looking closer at my error at the far right I see that I'm missing libnss3.so.  I'm trying installing that and seeing if it works.

Sorry for not looking closer at the error output

**Comment by UtahDave** [comment]
OK, so I had to run `vhs < idem.tape` multiple times and install the following dependencies as they popped up in the similar above error.
 `apt install libatk1.0-0`
`apt install libatk-bridge2.0-0`
`apt install libcups2`
`apt install libxcomposite1`
`apt install libxdamage1`

Then at the end I got to this error:

```
root@idemvhs:~/vhsstuff# vhs < idem.tape 
panic: [launcher] Failed to get the debug url: [1028/212222.508769:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


goroutine 1 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0xd80b20?, 0xc0006a8190?})
	/home/runner/go/pkg/mod/github.com/go-rod/rod@v0.112.0/lib/utils/utils.go:60 +0x25
github.com/go-rod/rod/lib/utils.E(...)
	/home/runner/go/pkg/mod/github.com/go-rod/rod@v0.112.0/lib/utils/utils.go:66
github.com/go-rod/rod/lib/launcher.(*Launcher).MustLaunch(0xc000168000?)
	/home/runner/go/pkg/mod/github.com/go-rod/rod@v0.112.0/lib/launcher/launcher.go:351 +0x67
main.New()
	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.1/vhs.go:67 +0x27b
main.Evaluate({0xc000738000, 0x864}, {0x1454480, 0xc000012018}, {0x0, 0x0, 0x0?})
	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.1/evaluator.go:33 +0x1c5
main.glob..func1(0x1a1b320?, {0x1a6f590, 0x0, 0x0?})
	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.1/main.go:60 +0x16d
github.com/spf13/cobra.(*Command).execute(0x1a1b320, {0xc000022230, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x1a1b320)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
main.main()
	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.1/main.go:135 +0x25
```

Is this a completely different error?

**Comment by maaslalani** [comment]
> OK, so I had to run `vhs < idem.tape` multiple times and install the following dependencies as they popped up in the similar above error.
> 
>  `apt install libatk1.0-0`
> 
> `apt install libatk-bridge2.0-0`
> 
> `apt install libcups2`
> 
> `apt install libxcomposite1`
> 
> `apt install libxdamage1`
> 
> 
> 
> Then at the end I got to this error:
> 
> 
> 
> ```
> 
> root@idemvhs:~/vhsstuff# vhs < idem.tape 
> 
> panic: [launcher] Failed to get the debug url: [1028/212222.508769:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
> 
> 
> 
> 
> 
> goroutine 1 [running]:
> 
> github.com/go-rod/rod/lib/utils.glob..func2({0xd80b20?, 0xc0006a8190?})
> 
> 	/home/runner/go/pkg/mod/github.com/go-rod/rod@v0.112.0/lib/utils/utils.go:60 +0x25
> 
> github.com/go-rod/rod/lib/utils.E(...)
> 
> 	/home/runner/go/pkg/mod/github.com/go-rod/rod@v0.112.0/lib/utils/utils.go:66
> 
> github.com/go-rod/rod/lib/launcher.(*Launcher).MustLaunch(0xc000168000?)
> 
> 	/home/runner/go/pkg/mod/github.com/go-rod/rod@v0.112.0/lib/launcher/launcher.go:351 +0x67
> 
> main.New()
> 
> 	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.1/vhs.go:67 +0x27b
> 
> main.Evaluate({0xc000738000, 0x864}, {0x1454480, 0xc000012018}, {0x0, 0x0, 0x0?})
> 
> 	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.1/evaluator.go:33 +0x1c5
> 
> main.glob..func1(0x1a1b320?, {0x1a6f590, 0x0, 0x0?})
> 
> 	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.1/main.go:60 +0x16d
> 
> github.com/spf13/cobra.(*Command).execute(0x1a1b320, {0xc000022230, 0x0, 0x0})
> 
> 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:916 +0x862
> 
> github.com/spf13/cobra.(*Command).ExecuteC(0x1a1b320)
> 
> 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x3bd
> 
> github.com/spf13/cobra.(*Command).Execute(...)
> 
> 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
> 
> main.main()
> 
> 	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.1/main.go:135 +0x25
> 
> ```
> 
> 
> 
> Is this a completely different error?

Are you running VHS as a root user @UtahDave? If you are can you try switching to a non-root user to see if that fixes things?

**Comment by UtahDave** [comment]
> > OK, so I had to run `vhs < idem.tape` multiple times and install the following dependencies as they popped up in the similar above error.
> > `apt install libatk1.0-0`
> > `apt install libatk-bridge2.0-0`
> > `apt install libcups2`
> > `apt install libxcomposite1`
> > `apt install libxdamage1`
> > Then at the end I got to this error:
> > ```
> > 
> > root@idemvhs:~/vhsstuff# vhs < idem.tape 
> > 
> > panic: [launcher] Failed to get the debug url: [1028/212222.508769:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
> > 
> > 
> > 
> > 
> > 
> > goroutine 1 [running]:
> > 
> > github.com/go-rod/rod/lib/utils.glob..func2({0xd80b20?, 0xc0006a8190?})
> > 
> > 	/home/runner/go/pkg/mod/github.com/go-rod/rod@v0.112.0/lib/utils/utils.go:60 +0x25
> > 
> > github.com/go-rod/rod/lib/utils.E(...)
> > 
> > 	/home/runner/go/pkg/mod/github.com/go-rod/rod@v0.112.0/lib/utils/utils.go:66
> > 
> > github.com/go-rod/rod/lib/launcher.(*Launcher).MustLaunch(0xc000168000?)
> > 
> > 	/home/runner/go/pkg/mod/github.com/go-rod/rod@v0.112.0/lib/launcher/launcher.go:351 +0x67
> > 
> > main.New()
> > 
> > 	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.1/vhs.go:67 +0x27b
> > 
> > main.Evaluate({0xc000738000, 0x864}, {0x1454480, 0xc000012018}, {0x0, 0x0, 0x0?})
> > 
> > 	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.1/evaluator.go:33 +0x1c5
> > 
> > main.glob..func1(0x1a1b320?, {0x1a6f590, 0x0, 0x0?})
> > 
> > 	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.1/main.go:60 +0x16d
> > 
> > github.com/spf13/cobra.(*Command).execute(0x1a1b320, {0xc000022230, 0x0, 0x0})
> > 
> > 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:916 +0x862
> > 
> > github.com/spf13/cobra.(*Command).ExecuteC(0x1a1b320)
> > 
> > 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x3bd
> > 
> > github.com/spf13/cobra.(*Command).Execute(...)
> > 
> > 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
> > 
> > main.main()
> > 
> > 	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.1/main.go:135 +0x25
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is this a completely different error?
> 
> Are you running VHS as a root user @UtahDave? If you are can you try switching to a non-root user to see if that fixes things?

I am running as root. This is an LXC container with only a root user.

I'll add a non-root user and see if that helps.

**Comment by UtahDave** [comment]
I added a non-root user and it worked great. I'm going to start over with a fresh container and start the install process with a non-root user and see if I still have to install all those dependencies.

Is there a reason why vhs cannot work while running as root?

**Comment by maaslalani** [comment]
Not sure, I believe something to do with root and `--no-sandbox` flag that go-rod uses:

Running as root without --no-sandbox is not supported. See https://crbug.com/638180

**Comment by ysmood** [comment]
@maaslalani You can add this flag, rod supports it:

```go
launcher.New().NoSandbox().MustLaunch()
```

Check the doc for more info

**Comment by skchronicles** [comment]
Hello there,

I am also running into the same issue while using the docker image listed in your README. I pulled this docker image, `ghcr.io/charmbracelet/vhs`, today using singularity, and I am getting the same error. 

Here is the command I am running:
```
$ singularity exec -B $PWD SIFs/vhs_latest.sif vhs /data/OpenOmics/dev/bin/demo.tape

File: /data/OpenOmics/dev/bin/demo.tape
panic: [launcher] Failed to get the debug url: The setuid sandbox is not running as root. Common causes:
  * An unprivileged process using ptrace on it, like a debugger.
  * A parent process set prctl(PR_SET_NO_NEW_PRIVS, ...)
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
[0100/000000.694421:ERROR:zygote_linux.cc(650)] write: Broken pipe (32)


goroutine 1 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0xd80b20?, 0xc0006160c0?})
	/home/runner/go/pkg/mod/github.com/go-rod/rod@v0.112.0/lib/utils/utils.go:60 +0x25
github.com/go-rod/rod/lib/utils.E(...)
	/home/runner/go/pkg/mod/github.com/go-rod/rod@v0.112.0/lib/utils/utils.go:66
github.com/go-rod/rod/lib/launcher.(*Launcher).MustLaunch(0xc0000b00e0?)
	/home/runner/go/pkg/mod/github.com/go-rod/rod@v0.112.0/lib/launcher/launcher.go:351 +0x67
main.New()
	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.1/vhs.go:67 +0x27b
main.Evaluate({0xc0004ac900, 0x85b}, {0x1454480, 0xc000012018}, {0x0, 0x0, 0x0?})
	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.1/evaluator.go:33 +0x1c5
main.glob..func1(0x1a1b320?, {0xc000448590, 0x1, 0x1?})
	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.1/main.go:60 +0x16d
github.com/spf13/cobra.(*Command).execute(0x1a1b320, {0xc000022050, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x1a1b320)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
main.main()
	/home/runner/go/pkg/mod/github.com/charmbracelet/vhs@v0.1.1/main.go:135 +0x25
```

Were you able to fix this issue in your docker image? Please let me know what you think.

Best Regards,
@skchronicles
