### ISSUE TITLE
Publish command stalls (server unresponsive?)

### ISSUE THREAD

**Issue by leg100** [charmbracelet/vhs#472]
**Describe the bug**

I'm trying to publish a gif created with `vhs`, but it hangs/stalls/freezes, without any output.

**Setup**

Arch linux, bash, alacritty

**To Reproduce**

`vhs publish demo.gif`

....And then it just stalls. In fact, the only way to stop it is to send it a SIGKILL:

`pkill -9 -f vhs`

It looks like the server is unresponsive:

```
> sudo netstat -tp
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
...
tcp        0      1 tower:32986             ec2-3-232-162-202.c:ssh SYN_SENT    601581/vhs          
```

Update: after a while, `vhs publish` does output:

```
dial tcp 3.232.162.202:22: connect: connection timed out
```

But it still stalls and I still need to send it a SIGKILL.

**Comment by leg100** [comment]
Hello @maaslalani, yes it is very much working now. Appreciated!

**Comment by maaslalani** [comment]
Awesome glad to hear! The fix was all thanks to @aymanbagabas!
