### ISSUE TITLE
VHS Logomarks

### ISSUE THREAD

**Issue by rayhanadev** [charmbracelet/vhs#56]
Heya! I create templates for the the popular IDE [Replit](https://replit.com/) and saw VHS in my feed and thought, "Wow, this stuff is really cool!" so I went ahead and made a template for [VHS on Replit](https://replit.com/@RayhanADev/VHS?v=1).

I was wondering if you had (or could make) a square logo for VHS when you get a chance, it would help with making the template icon neater and would be a nice addition to VHS' branding overall :).

**Comment by maaslalani** [comment]
Hey @rayhanadev thanks for doing this!

Here is a square version of the logo:


<img src="https://user-images.githubusercontent.com/42545625/198459509-983881b1-6fcb-4f7e-a8dd-7450f4246df5.png" width="100" />

**Comment by rayhanadev** [comment]
Good stuff :) 👍
