### ISSUE TITLE
Package not found on AUR

### ISSUE THREAD

**Issue by ghostx31** [charmbracelet/vhs#57]
Hello, thanks for this project!

The project is currently not present in the AUR if I'm not mistaken? The `README.md` says to install the package `vhs` from AUR but it is not found. But Carlos seems to have added [vhs-bin](https://aur.archlinux.org/packages/vhs-bin) but its dependencies are not added properly since it depends on `ttyd` and `ffmpeg`.

**Comment by muesli** [comment]
> The project is currently not present in the AUR if I'm not mistaken? The `README.md` says to install the package `vhs` from AUR but it is not found.

Thanks for the heads up, we'll fix the README, as you realized it's `vhs-bin` indeed.

> But Carlos seems to have added [vhs-bin](https://aur.archlinux.org/packages/vhs-bin) but its dependencies are not added properly since it depends on `ttyd` and `ffmpeg`.

Dependencies have been added and will be fixed in the next release.

**Comment by grawlinson** [comment]
Additionally, I've just added `vhs` to the AUR, for these that like compiling from source (*who* does that!?)

**Comment by muesli** [comment]
> Additionally, I've just added `vhs` to the AUR, for these that like compiling from source (_who_ does that!?)

Thank you George! (I do!)
