### ISSUE TITLE
Allow for multiple files/types in vhs serve

### ISSUE THREAD

**Issue by jolheiser** [charmbracelet/vhs#59]
Currently `vhs serve` forces and returns a gif regardless of `Output`. 
It would be interesting to allow for multiple (or at least choose an alternative), which would then be streamed back as a single archive of files.

From a glance at the code I think it should be possible to check if there are multiple outputs and, if so, create an archive to return instead of the bytes of a single file.

-----

I would be interested in getting my feet a little wet if you find this proposal worth pursuing. :slightly_smiling_face:

**Comment by maaslalani** [comment]
I think at the very least we should allow for different file formats (not just force GIFs).

So if a tape file specifies a `.mp4` but not `.gif` we should return the mp4 from the VHS server. I.e. return whichever output is specified or GIFs by default.
