### ISSUE TITLE
Unauthorized to pull Docker image

### ISSUE THREAD

**Issue by TymekDev** [charmbracelet/vhs#61]
Hey, I wanted to give vhs a spin via Docker, but I am getting the following error when trying to pull the image:

```
Error response from daemon: Head "https://ghcr.io/v2/charmbracelet/vhs/manifests/latest": unauthorized.
```

**Comment by Johnzzon** [comment]
I also encountered this. After some digging it seemed like you need to authorize GitHub Packages. So I created a PAT for GitHub and logged in via the docker login command. It succeeded, but still not allowed to pull the image. I'm getting the following error:
```
$ docker run --rm -v $PWD:/vhs ghcr.io/charmbracelet/vhs test.tape
Unable to find image 'ghcr.io/charmbracelet/vhs:latest' locally
docker: Error response from daemon: denied.
See 'docker run --help'.
```

**Comment by caarlos0** [comment]
fixed, should be public now!

Thanks for letting us know :)

**Comment by maaslalani** [comment]
Thanks so much for reporting this @TymekDev and for confirming @Johnzzon ❤️

**Comment by Johnzzon** [comment]
Awesome, thanks for a quick fix! Can confirm that it's working now :)
