### ISSUE TITLE
Support multi-line commands

### ISSUE THREAD

**Issue by jacobtomlinson** [charmbracelet/vhs#68]
I'd love to see support long commands and choose where the line breaks happen.

```console
$ mamba install -y python=3.11 \
    foo bar baz 
```

It seems VHS doesn't support this, I tried the following.

```
# This includes the `\\ \n` characters in the command

Type "mamba install -y python=3.11 \\ \n foo bar baz"
```

```
# This gives a 'Error: parse error'

Type "mamba install -y python=3.11 \
foo bar baz"
```

**Comment by michaeltlombardi** [comment]
Being able to use here-strings or equivalent would be great, I use multiline commands _often_ for readability in my examples.

**Comment by maaslalani** [comment]
You can do this with:

```
Type "mamba install -y python=3.11 \"
Enter
Type "foo bar baz"
```

**Comment by maaslalani** [comment]
![out](https://user-images.githubusercontent.com/42545625/198739265-57425654-7fb9-4d74-9fe8-ff93a2c73ee7.gif)

**Comment by maaslalani** [comment]
Feel free to reopen this issue if that's not the correct solution to what you're asking about.

**Comment by jacobtomlinson** [comment]
Oh yeah, I didn't think of that. Thanks! Thinking about things in terms of key presses instead of characters is a bit of a mindset change.

I wonder if it would be valuable to users to make `Type "\n"` equivalent to `Enter`?

**Comment by jamesowers-cohere** [comment]
With apologies this is off topic for this issue...

@jacobtomlinson I'm struggling to get mamba/conda to play nice in my .tape because the shell is launched with `--noprofile --norc`

https://github.com/charmbracelet/vhs/blob/bea7f77ab4cf5e6439aa33709bb5c6e25a4b707c/shell.go#L24

How did you get it to work nicely?

**Comment by jacobtomlinson** [comment]
@jamesowers-cohere it's been a couple of years since I tried this, so things may have broken since then.
