### ISSUE TITLE
Set GIF quality

### ISSUE THREAD

**Issue by jacobtomlinson** [charmbracelet/vhs#69]
All the GIFs I'm getting seem a little blurry. Is there any way to set the quality?

```
Output doc/source/images/operator-install.gif

Set FontSize 18
Set Width 1200
Set Height 200
Set Padding 20
Set TypingSpeed 25ms

Type "helm install --wait --repo https://helm.dask.org --create-namespace -n dask-operator --generate-name dask-kubernetes-operator"

Sleep 500ms

Enter

Sleep 5s

Enter
Type "kubectl get daskclusters"

Sleep 500ms

Enter

Sleep 2s

Enter
Type "kubectl get pods -A -l app.kubernetes.io/name=dask-kubernetes-operator"

Sleep 500ms

Enter

Sleep 5s
```

![operator-install](https://user-images.githubusercontent.com/1610850/198572196-382b914a-0326-41c4-8508-a7f14d91320e.gif)

**Comment by maaslalani** [comment]
One thing you can try is to increase the `Height` and `Width` and increase the `FontSize` and then scale it down after.

```
Set Height 2400
Set Width 400
Set FontSize 36
```

**Comment by maaslalani** [comment]
I think there might be a few things we can do somethings on our end regarding font anti-aliasing, etc... as well

**Comment by maaslalani** [comment]
@jacobtomlinson This is what I get when I run the VHS with the following settings:

```Elixir
Set FontSize 36
Set Width 2400
Set Height 400
Set Padding 40
```

I doubled all the values and it came out crispier. Hope that helps!

![operator-install](https://user-images.githubusercontent.com/42545625/198839220-212b69ac-efce-4c06-8d15-1ee355c2d98d.gif)

**Comment by jacobtomlinson** [comment]
Oooh that's much better, thanks @maaslalani!

**Comment by dimk90** [comment]
> [@jacobtomlinson](https://github.com/jacobtomlinson) This is what I get when I run the VHS with the following settings:
> 
> Set FontSize 36
> Set Width 2400
> Set Height 400
> Set Padding 40
> I doubled all the values and it came out crispier. Hope that helps!
> 
> ![operator-install](https://user-images.githubusercontent.com/42545625/198839220-212b69ac-efce-4c06-8d15-1ee355c2d98d.gif) [ ![operator-install](https://user-images.githubusercontent.com/42545625/198839220-212b69ac-efce-4c06-8d15-1ee355c2d98d.gif) ](https://user-images.githubusercontent.com/42545625/198839220-212b69ac-efce-4c06-8d15-1ee355c2d98d.gif) [ ](https://user-images.githubusercontent.com/42545625/198839220-212b69ac-efce-4c06-8d15-1ee355c2d98d.gif)

Oh, this 2× resolution workaround reveals an even more annoying problem: playback speed changes with the resolution 🤦. Adjusting the resolution should not change the recording’s timing or duration.

**Comment by dimk90** [comment]
`tmux` + [`asciinema`](https://github.com/asciinema/asciinema) + [`agg`](https://github.com/asciinema/agg) avoids both problems here - no GIF quality loss and no timing drift at higher resolutions. Wiring them by hand is more work than a `.tape`, so there is [S-VHS](https://github.com/dimk90/s-vhs), a small bash wrapper providing a tape-like recording style.
