### ISSUE TITLE
True color support?

### ISSUE THREAD

**Issue by willmcgugan** [charmbracelet/vhs#76]
I've seen some output from vhs, and it looks like it is rendering the terminal output with 256 colors.

Would it be possible to enable truecolor terminal output, and color reduce the palette to 256 colors for the gif? 

A little context:

https://twitter.com/willmcgugan/status/1586017649649012737

**Comment by Delta456** [comment]
For this to work wouldn't the Terminal need to support/have 24 bit color? I find this idea to be great though.

**Comment by maaslalani** [comment]
I actually tried out a script that tries to print out a full colour gradient and it looks like we do support truecolor:

```
#!/bin/bash
awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
    for (colnum = 0; colnum<77; colnum++) {
        r = 255-(colnum*255/76);
        g = (colnum*510/76);
        b = (colnum*255/76);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
}'
```

![true-color](https://user-images.githubusercontent.com/42545625/198854245-a50f3fea-b0c7-4452-8337-ebe8ccd135be.gif)

For reference, this is what it looks like on my terminal.

<img width="915" alt="image" src="https://user-images.githubusercontent.com/42545625/198854285-c685edc3-d267-4bd7-86c4-29004c2703c7.png">

**Comment by maaslalani** [comment]
Feel free to reopen this issue if the true color support is not working for you!

**Comment by meowgorithm** [comment]
@willmcgugan out if curiosity, what terminal are you using with VHS? Additionally, are you using a multiplexer?
