### ISSUE TITLE
Support rendering offset

### ISSUE THREAD

**Issue by muesli** [charmbracelet/vhs#8]
Support starting the rendering a few seconds into the recording, then looping around from the end to the beginning.

The idea behind this is that it generates a more reasonable thumbnail when sharing the gif on various platforms. The viewer won't typically notice this *if* the output is running as a continuous loop.

**Comment by griimick** [comment]
@maaslalani We can use the `-start_number` option to set the starting frame in [ffmpeg image2](http://underpop.online.fr/f/ffmpeg/help/image2-1.htm.gz) and move the frames which are before it to end of the sequence by renaming their file names. 


![image](https://user-images.githubusercontent.com/10350864/198894536-ec61d8f5-0cdf-4714-87b0-8221b3044ccb.png)

I would like to take a crack at this if you agree.

**Comment by maaslalani** [comment]
@griimick Sounds perfect to me!

**Comment by maaslalani** [comment]
To start we can just do # of frames, if that's easier for you!
