### ISSUE TITLE
Wrong number of lines in case of CRLF files

### ISSUE THREAD

**Issue by abhijit-hota** [charmbracelet/vhs#80]
The `isNewLine` function below checks for `\r` and `\n` separately. 

https://github.com/charmbracelet/vhs/blob/ab65901d8f2301e7585f482b2514b62a62cf86e8/lexer.go#L204-L207

The CRLF line ending is `\r\n` and hence, the line count doubles as they are **counted as two different newlines** here:

https://github.com/charmbracelet/vhs/blob/ab65901d8f2301e7585f482b2514b62a62cf86e8/lexer.go#L151-L162

This messes up error logs and sometimes gives out of range errors due to this code here:

https://github.com/charmbracelet/vhs/blob/1a3529697527c3f5f2563c8d8a097c45491d2880/main.go#L116

**Comment by maaslalani** [comment]
Ah this should be:

```
    return ch == '\n' || ch == '\r\n'
```

Correct?

**Comment by abhijit-hota** [comment]
Yes, but `ch` is a `byte` and `\r` and `\n` are 2 bytes.

**Comment by caarlos0** [comment]
@abhijit-hota could you check #90?

**Comment by maaslalani** [comment]
@abhijit-hota Another solution proposed with #91
