### ISSUE TITLE
Windows: Bash just throw back if WSL not installed

### ISSUE THREAD

**Issue by Rebzzel** [charmbracelet/vhs#93]
Hey! Nice tool.
But I found one painful bug on Windows.
This bug is not entirely obvious, because the build is successful:
```
File: demo.tape
Output .gif demo.gif
Set FontSize 46
Set Width 1200
Set Height 600
Type echo 'Welcome to VHS!'
Sleep 500ms
Enter 1
Sleep 5s
Creating GIF...
```

But at the output gif we see this:
![demo](https://user-images.githubusercontent.com/30433331/198847105-ab7cde1a-ebe9-43af-9215-e34081a5f5a4.gif)

I found that this is due to the fact that WSL is not installed on my machine, and `bash` command just throws me back out:
![bash](https://user-images.githubusercontent.com/30433331/198847583-96bf4c83-798d-434f-b100-9c82317e1f0a.gif)

The solution, I think, is obvious to you: run `cmd` or `powershell` instead of `bash` on Windows machines.
https://github.com/charmbracelet/vhs/blob/cf3919b5f5f6f78ff39c08aa28fd4a2a8b071f87/tty.go#L34

I know that you are preparing a feature (Set-Shell) but keep in mind that if the Set-Shell was not explicitly specified in the file, it should be selected automatically depending on the OS.

Thank you!
Have a nice day!

**Comment by maaslalani** [comment]
That is a really good point about having different defaults for different operating systems! We should definitely do this! Thank you for the suggestion.

**Comment by Delta456** [comment]
On Windows, the default Terminal needs to be Command Prompt or Powershell 5.
